# conda environment description file for AtlantisCmd package testing environment
#
# Creates a conda environment in which the AtlantisCmd package unit tests,
# coverage analysis, and docs link checks can be run.
# Primarily intended for creation of a conda env for use in a GitHub Actions workflows.

name: atlantis-cmd-test

channels:
  - conda-forge
  - nodefaults

dependencies:
  - arrow
  - cliff
  - cookiecutter
  - f90nml
  - gitpython
  - pip
  - pyyaml

  # For unit tests
  - coverage
  - pytest-cov
  - pytest-randomly

  # For documentation links checking
  - sphinx==8.1.3
  - sphinx-notfound-page==1.0.4
  - sphinx-rtd-theme==3.0.0

  - pip:
    - python-hglib

    # install NEMO-Cmd and AtlantisCmd packages in editable mode
    - git+https://github.com/SalishSeaCast/NEMO-Cmd.git#egg=NEMO-Cmd
    - --editable ../
