name: sphinx-linkcheck

on:
  push:
    branches: ['*']
  schedule:
    - cron: 43 4 12 * *  # 04:43 UTC on the 12th day of each month

jobs:
  sphinx-linkcheck:
    name: linkcheck docs
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2


      - name: Create conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
           auto-update-conda: true
           auto-activate-base: false
           channel-priority: strict
           environment-file: envs/environment-test.yaml
           python-version: ${{ matrix.python-version }}
           activate-environment: atlantis-cmd-test

      - name: Install package
        shell: bash -l {0}
        run: |
          python3 -m pip install --editable $GITHUB_WORKSPACE

      - name: linkcheck docs
        shell: bash -l {0}
        run: |
          (cd docs && make linkcheck)

      - name: Push job status to SalishSeaCast Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: Sphinx linkcheck
          fields: repo,eventName,ref,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_SALISHSEACAST_WEBHOOK_URL }}
        if: always()
